### ISSUE TITLE
Download the paper

### ISSUE THREAD

**Issue by yidamyth** [mogvision/hvit#1]
Excuse me, where can i download this paper ? Can't find it in arXiv.

**Comment by mogvision** [comment]
Hi and thanks for your interest in this work. 
I'm on vacation, away from work. When I return, I'll update my Git repo. 
BWs

**Comment by yidamyth** [comment]
> Hi and thanks for your interest in this work. I'm on vacation, away from work. When I return, I'll update my Git repo. BWs

Thanks for your reply, hope your Git repo. Wish you have one good vacation.
